### Create Product

POST http://localhost:8080/odata/v4/AdminService/Product
##OData 서비스 경로와 엔티티 이름은 대소문자를 포함해 정확히 일치해야함
Content-Type: application/json

{
    "ID": 42, 
    "title": "My Tutorial Product", 
    "descr": "You are doing an awesome job!"
}

### Create Categories

POST http://localhost:8080/odata/v4/AdminService/Categories
Content-Type: application/json

{
    "ID": 1, 
    "name": "TechEd", 
    "descr": "TechEd related topics", 
    "children": [
        {"ID": 10, "name": "CAP Java", "descr": "Run on Java"}, 
        {"ID": 11, "name": "CAP Node.js", "descr": "Run on Node.js"}
    ]
}
